name: Build Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract branch name
        run: |
          export BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo "##[set-output name=branch;]$BRANCH_NAME"
          if [ $BRANCH_NAME = "main" ] || [ $BRANCH_NAME = "master" ]
            then echo "##[set-output name=tag;]latest"
            else echo "##[set-output name=tag;]$BRANCH_NAME"
          fi
        id: extract_branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up image name
        run: |
          GHRC_IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]') 
          DOCKER_IMAGE_NAME=$(echo "${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]') 
          echo "::set-output name=GHRC_IMAGE_NAME::$GHRC_IMAGE_NAME" 
          echo "::set-output name=DOCKER_IMAGE_NAME::$DOCKER_IMAGE_NAME"
        id: image-name

      - name: Build image And Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          # ,linux/arm
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          tags: |
            ${{ steps.image-name.outputs.GHRC_IMAGE_NAME }}:${{ steps.extract_branch.outputs.tag }}
            ${{ steps.image-name.outputs.DOCKER_IMAGE_NAME }}:${{ steps.extract_branch.outputs.tag }}
